// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFxNcczORHnfHchLXoI5h6OoMAqSQI9cA',
    appId: '1:297637392271:web:3e5795d5dabe758af8a5fa',
    messagingSenderId: '297637392271',
    projectId: 'socially-a4ddf',
    authDomain: 'socially-a4ddf.firebaseapp.com',
    storageBucket: 'socially-a4ddf.firebasestorage.app',
    measurementId: 'G-1VJLT82F2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYkYR_AqKvPvbLo2GH8rvo8XJjhib7Jhg',
    appId: '1:297637392271:android:a9938114883b516ff8a5fa',
    messagingSenderId: '297637392271',
    projectId: 'socially-a4ddf',
    storageBucket: 'socially-a4ddf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0udmM5zG0OrtsQAvl7LLECNud7eh1Jn8',
    appId: '1:297637392271:ios:4976c00c1247dac8f8a5fa',
    messagingSenderId: '297637392271',
    projectId: 'socially-a4ddf',
    storageBucket: 'socially-a4ddf.firebasestorage.app',
    iosBundleId: 'com.example.socially',
  );
}
